language: node_js
node_js:
- "node"

cache: npm

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run deploy

after_script:
  - npm run alias

global:
    secure: yNdVtIP6AvW5t4wDfFpvHDs7
